language: go

go:
  - 1.12.x
env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor'

git:
  depth: 1

install: true

before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GOPATH/bin

script:
  - go build ./...
  - go test ./...

after_success:
  - golangci-lint run


